### ISSUE TITLE
ImportError: cannot import name 'GPT4AllGPU' from 'nomic.gpt4all'

### ISSUE THREAD

**Issue by chuplares** [nomic-ai/nomic#122]
There is no reference for the class GPT4ALLGPU on the file **nomic/gpt4all/__init__.py** 

After adding the class, the problem went away.

For anyone with this problem, just make sure you init file looks like this:

`from nomic.gpt4all import GPT4All, GPT4AllGPU, prompt
`
Edit: Typo. Thanks for bringing that to my attention @mir-ashiq !

**Comment by mir-ashiq** [comment]
> 
cd nomic
from nomic.gpt4all.gpt4all import GPT4AllGPU

**Comment by mir-ashiq** [comment]
@chuplares 
from nomic.gpt4all.gpt4all import GPT4All, GPT4AllGPU, prompt
