### ISSUE TITLE
Not raising value error if id field is too long.

### ISSUE THREAD

**Issue by EdAyers** [nomic-ai/nomic#147]
I'm getting `'pyarrow.lib.ChunkedArray' object has no attribute 'utf8_length'` at this line instead of it raising the error on the next line when I have an id field that is too long.

https://github.com/nomic-ai/nomic/blob/4af847f2de75551afaef5132f7d1f84f786ab65d/nomic/project.py#L257

## mwe

```python
# nomic 1.1.6
# python 3.10.10
# pyarrow 11.0.0
from nomic import atlas
import numpy as np

project = atlas.AtlasProject(
    name="asdf",
    modality="embedding",
    unique_id_field="id",
    reset_project_if_exists=True,
)

embeddings = np.random.rand(273, 384)
data = [{"id": "hello {i}" * 128} for i in range(273)]

project.add_embeddings(embeddings=embeddings, data=data)
```

**Comment by AndriyMulyar** [comment]
Merged. Closing.
