### ISSUE TITLE
Specify language for topic labels

### ISSUE THREAD

**Issue by todochenxi** [nomic-ai/nomic#165]
Hello, can you tell me how to make the title as shown in the picture? Thank you very much!
![2023-06-05_21-32](https://github.com/nomic-ai/nomic/assets/108149467/7ff39998-5a61-413c-b93f-fcac681690f3)

**Comment by todochenxi** [comment]
Thanks for your reply. I have received an elegant visualization.

**Comment by todochenxi** [comment]
Actually, I noticed that these topics_ Labels come in different languages, such as English and Chinese, but my_text_field is in Chinese, how can I make the topic_ labels are all in Chinese.

**Comment by bmschmidt** [comment]
Currently our generative model is hard coded for English--I've changed the name of this issue to reflect the goal of allowing multiple languages for topic label generation, of which Chinese would certainly be one.

**Comment by todochenxi** [comment]
Thanks for your reply! I have to say that this is a very cool job, and I am looking forward to the release of new features!
