### ISSUE TITLE
Your authorization token is no longer valid. Run `nomic login` to obtain a new one.

### ISSUE THREAD

**Issue by liangyuxin42** [nomic-ai/nomic#199]
I keep getting this error message when I try to run the basic example in atlas document in jupyter notebook.
I run the following code cell by cell:
`!nomic login`
`!nomic login [token i got]`
(no error here)
```from nomic import atlas
import numpy as np

num_embeddings = 10000
embeddings = np.random.rand(num_embeddings, 256)

project = atlas.map_embeddings(embeddings=embeddings)
```

then I get this error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1642635/3339716498.py in 
      6 embeddings = np.random.rand(num_embeddings, 256)
      7 
----> 8 project = atlas.map_embeddings(embeddings=embeddings)

[~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/atlas.py](https://vscode-remote+ssh-002dremote-002b192-002e168-002e81-002e12.vscode-resource.vscode-cdn.net/cognitive_comp/liangyuxin/projects/RLHF_Analysis/~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/atlas.py) in map_embeddings(embeddings, data, id_field, name, description, is_public, colorable_fields, build_topic_model, topic_label_field, num_workers, organization_name, reset_project_if_exists, add_datums_if_exists, shard_size, projection_n_neighbors, projection_epochs, projection_spread)
     82         } for _ in range(len(embeddings))]
     83 
---> 84     project = AtlasProject(
     85         name=project_name,
     86         description=description,

[~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/project.py](https://vscode-remote+ssh-002dremote-002b192-002e168-002e81-002e12.vscode-resource.vscode-cdn.net/cognitive_comp/liangyuxin/projects/RLHF_Analysis/~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/project.py) in __init__(self, name, description, unique_id_field, modality, organization_name, is_public, project_id, reset_project_if_exists, add_datums_if_exists)
    861 
    862         if organization_name is None:
--> 863             organization_name = self._get_current_users_main_organization()['nickname']
    864 
    865         results = self._get_existing_project_by_name(project_name=name, organization_name=organization_name)

[~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/project.py](https://vscode-remote+ssh-002dremote-002b192-002e168-002e81-002e12.vscode-resource.vscode-cdn.net/cognitive_comp/liangyuxin/projects/RLHF_Analysis/~/anaconda3/envs/lyx/lib/python3.8/site-packages/nomic/project.py) in _get_current_users_main_organization(self)
    122         '''
    123 
--> 124         user = self._get_current_user()
...
---> 99             raise ValueError("Your authorization token is no longer valid. Run `nomic login` to obtain a new one.")
    100 
    101         return response.json()

ValueError: Your authorization token is no longer valid. Run `nomic login` to obtain a new one.

I will appreciate if you can provide some insight or solution to this problem!

**Comment by AndriyMulyar** [comment]
This should no longer be an issue
