### ISSUE TITLE
Different Topic option using api

### ISSUE THREAD

**Issue by suhmily** [nomic-ai/nomic#247]
I wonder why other data maps' topic options are [board, medium, specific] (i.e. https://atlas.nomic.ai/map/c1b88b47-2d9b-47e0-9002-b80766792582/2560fd25-52fe-42f1-a58f-ff5eccc890d2), while mine's are [topic1, topic2] (i.e. https://atlas.nomic.ai/map/63c51091-d265-40ca-b61c-cd920329db29/79e5e96a-d7c4-478c-a4af-a6b29f4cddef) even using same api code 
My python code is as below: 
project = atlas.map_text(data=table.sample(n = 5000).to_dict('records'),
                          indexed_field='question',
                          name='v0',
                          description='A description of the data.',
                          colorable_fields=['response'],
                          reset_project_if_exists=True,
                          )

**Comment by AndriyMulyar** [comment]
That is likely an old dataset. The topics were named this in an earlier release of Atlas.
