### ISSUE TITLE
[BUG] Error when adding new data into existing dataset througy Python SDK

### ISSUE THREAD

**Issue by catle2aurecon** [nomic-ai/nomic#364]
There is a bug in nomic package 3.3.3. The bug happens when I am trying to add new data into existing dataset.

* When existing dataset is loaded, self._schema does not exist. 
* When trying to add data into the existed map, python sdk nomic package checks for attribute self._schema. It leads to raised error

![Image](https://github.com/user-attachments/assets/671c11ae-b5d6-4e2c-ae44-61a21514dbf0)

My recommendation for a fix is as follows. 
 
```
    @property
    def schema(self) -> Optional[pa.Schema]:
        if self.__dict__.get("_schema") is not None:
            return self._schema
        if "schema" in self.meta and self.meta["schema"] is not None:
            self._schema: pa.Schema = ipc.read_schema(io.BytesIO(base64.b64decode(self.meta["schema"])))
            return self._schema
        return None
```

Please feel free to reach out for clarification.

**Comment by wilson-nomic** [comment]
Hey @catle2aurecon, thanks for raising, we've applied a fix now which should be released shortly.
